### PR TITLE
Shows reviewers in a PR

### PR DESCRIPTION
**Pull request by nikitap492**
Related issue: https://github.com/palyuga/BitbucketHelper4Idea/issues/4

### CODE REVIEW

**Comment by dskopylov** [comment]
Please create a ticket (or fix here if you want:-)) to show avas of approved/need_works users in the beginning of the avas list

**Review by dskopylov — APPROVED** [review]

**Comment by nikitap492** [comment]
Thank you, It would be really helpful. But I am afraid that old bitbucket api doesn't have flag "Need work". However, it might be that I missed it
I am going to write reordering in the issue

**Comment by nikitap492** [comment]
I am unable to merge this PR
@palyuga, Could you help me to do it?

**Comment by palyuga** [comment]
@nikitap492 I cannot merge it now because of the new conflicts. Could you resolve them?

**Comment by nikitap492** [comment]
@palyuga, resolved

**Pull request merged**
